import "@mantine/core/styles.css";
import "@/app/main.css";
import "@mantine/carousel/styles.css";
import "@mantine/notifications/styles.css";
import "aos/dist/aos.css";
// import "@mantine/dropzone/styles.css";
import type { Metadata } from "next";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import Providers from "@/utils/provider";
import { Notifications } from "@mantine/notifications";
import { ModalsProvider } from "@mantine/modals";

export const metadata: Metadata = {
  title: "Vitrine do ISPB",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>

      <body className="">
        <MantineProvider>
          <ModalsProvider labels={{ confirm: "Submit", cancel: "Cancel" }}>
            <Notifications />
            <Providers>{children}</Providers>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
